name: Code-Romeo-CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            build_type: Release
          - os: windows-latest
            c_compiler: cl
            build_type: Debug
          - os: windows-latest
            c_compiler: clang-cl
            build_type: Release
          - os: windows-latest
            c_compiler: clang-cl
            build_type: Debug
          - os: windows-latest
            c_compiler: clang
            build_type: Release
          - os: windows-latest
            c_compiler: clang
            build_type: Debug

          - os: ubuntu-latest
            c_compiler: gcc
            build_type: Release
          - os: ubuntu-latest
            c_compiler: gcc
            build_type: Debug
          - os: ubuntu-latest
            c_compiler: clang
            build_type: Release
          - os: ubuntu-latest
            c_compiler: clang
            build_type: Debug

          - os: macos-latest
            c_compiler: gcc
            build_type: Release
          - os: macos-latest
            c_compiler: gcc
            build_type: Debug
          - os: macos-latest
            c_compiler: clang
            build_type: Release
          - os: macos-latest
            c_compiler: clang
            build_type: Debug

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code-Romeo (the library)
        uses: actions/checkout@v4
        with:
          path: 'Code-Romeo'
          submodules: 'recursive'

      - name: Checkout Code-Juliett (the application)
        uses: actions/checkout@v4
        with:
          repository: omerfuyar/Code-Juliett
          path: 'Code-Juliett'
          submodules: 'recursive'

      - name: Install Dependencies
        working-directory: Code-Juliett
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libwayland-dev libxkbcommon-dev wayland-protocols libx11-dev libxrandr-dev libxinerama-dev  libxcursor-dev libxi-dev libgl1-mesa-dev xvfb
          fi
        shell: bash

      - name: Add MSVC to PATH
        if: runner.os == 'Windows' && (matrix.c_compiler == 'cl' || matrix.c_compiler == 'clang-cl')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Swap Code-Romeo with the version under test
        run: |
          rm -rf Code-Juliett/dependencies/Romeo
          mv Code-Romeo Code-Juliett/dependencies/Romeo
        shell: bash

      - name: Configure and Build
        working-directory: Code-Juliett
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ${{ matrix.c_compiler }} shuildJuliett.c ${{ matrix.build_type == 'cl' && '' || '-o shuildJuliett.exe' }} 
          fi
          ./shuildJuliett ${{ matrix.c_compiler }} ${{ matrix.build_type == 'Debug' && 'd' || 'r' }}
        shell: bash

      - name: Run graphical app
        working-directory: Code-Juliett
        run: |
          BUILD_TYPE_LOWER=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a --server-args="-screen 0 1024x768x24" build/$BUILD_TYPE_LOWER/Code-Juliett &
            APP_PID=$!
            sleep 5
            kill $APP_PID
          elif [ "$RUNNER_OS" == "macOS" ]; then
            build/$BUILD_TYPE_LOWER/Code-Juliett &
            APP_PID=$!
            sleep 5
            kill $APP_PID
          elif [ "$RUNNER_OS" == "Windows" ]; then
            ./build/$BUILD_TYPE_LOWER/Code-Juliett.exe &
            APP_PID=$!
            sleep 5
            taskkill /F /PID $APP_PID
          fi
        shell: bash