name: Code-Romeo-CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            build_type: r
          - os: windows-latest
            c_compiler: cl
            build_type: d
          - os: windows-latest
            c_compiler: clang
            build_type: r
          - os: windows-latest
            c_compiler: clang
            build_type: d

          - os: ubuntu-latest
            c_compiler: gcc
            build_type: r
          - os: ubuntu-latest
            c_compiler: gcc
            build_type: d
          - os: ubuntu-latest
            c_compiler: clang
            build_type: r
          - os: ubuntu-latest
            c_compiler: clang
            build_type: d

          - os: macos-latest
            c_compiler: gcc
            build_type: r
          - os: macos-latest
            c_compiler: gcc
            build_type: d
          - os: macos-latest
            c_compiler: clang
            build_type: r
          - os: macos-latest
            c_compiler: clang
            build_type: d

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code-Romeo (the library)
        uses: actions/checkout@v4
        with:
          path: 'Code-Romeo'
          submodules: 'recursive'

      - name: Checkout Code-Juliett (the application)
        uses: actions/checkout@v4
        with:
          repository: omerfuyar/Code-Juliett
          path: 'Code-Juliett'
          submodules: 'recursive'

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libwayland-dev libxkbcommon-dev wayland-protocols libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev xvfb

      - name: Add MSVC to PATH
        if: runner.os == 'Windows' && matrix.c_compiler == 'cl'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Swap Code-Romeo with the version under test
        run: |
          rm -rf Code-Juliett/dependencies/Romeo
          mv Code-Romeo Code-Juliett/dependencies/Romeo
        shell: bash

      - name: Build shuildJuliett
        working-directory: Code-Juliett
        run: |
          ${{ matrix.c_compiler }} shuildJuliett.c -O3 -o shuildJuliett${{ runner.os == 'Windows' && '.exe' || '' }}
        shell: bash

      - name: Build Code-Juliett
        working-directory: Code-Juliett
        run: |
          ./shuildJuliett${{ runner.os == 'Windows' && '.exe' || '' }} ${{ matrix.c_compiler }} ${{ matrix.build_type }} all
        shell: bash

      - name: Run graphical app
        working-directory: Code-Juliett
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a --server-args="-screen 0 1024x768x24" build/${{ matrix.build_type }}/Code-Juliett &
            APP_PID=$!
            sleep 5
            kill $APP_PID
          elif [ "$RUNNER_OS" == "macOS" ]; then
            build/${{ matrix.build_type }}/Code-Juliett &
            APP_PID=$!
            sleep 5
            kill $APP_PID
          elif [ "$RUNNER_OS" == "Windows" ]; then
            ./build/${{ matrix.build_type }}/Code-Juliett.exe &
            APP_PID=$!
            sleep 5
            taskkill /F /PID $APP_PID
          fi
        shell: bash