name: Code-Romeo-CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            compiler: msvc
            c_compiler: cl
            build_type: Release
          - os: windows-latest
            compiler: msvc
            c_compiler: cl
            build_type: Debug
          - os: windows-latest
            compiler: clang-cl
            c_compiler: clang-cl
            build_type: Release
          - os: windows-latest
            compiler: clang-cl
            c_compiler: clang-cl
            build_type: Debug
          - os: windows-latest
            compiler: clang
            c_compiler: clang
            build_type: Release
          - os: windows-latest
            compiler: clang
            c_compiler: clang
            build_type: Debug

          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            build_type: Release
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            build_type: Debug
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            build_type: Release
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            build_type: Debug

          - os: macos-latest
            compiler: gcc
            c_compiler: gcc
            build_type: Release
          - os: macos-latest
            compiler: gcc
            c_compiler: gcc
            build_type: Debug
          - os: macos-latest
            compiler: clang
            c_compiler: clang
            build_type: Release
          - os: macos-latest
            compiler: clang
            c_compiler: clang
            build_type: Debug

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code-Romeo (the library)
        uses: actions/checkout@v4
        with:
          path: 'Code-Romeo'
          submodules: 'recursive'

      - name: Checkout Code-Juliett (the application)
        uses: actions/checkout@v4
        with:
          repository: omerfuyar/Code-Juliett
          path: 'Code-Juliett'
          submodules: 'recursive'

      - name: Install Dependencies
        working-directory: Code-Juliett
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install cmake ninja-build libwayland-dev libxkbcommon-dev wayland-protocols libx11-dev libxrandr-dev libxinerama-dev  libxcursor-dev libxi-dev pkgconf libgl1-mesa-dev xvfb
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install cmake ninja
          elif [ "$RUNNER_OS" == "Windows" ]; then
            winget install -e --id Kitware.CMake --accept-source-agreements --accept-package-agreements --silent
            winget install -e --id Ninja-build.Ninja --accept-source-agreements --accept-package-agreements --silent
            echo "C:\Program Files\CMake\bin" >> $env:GITHUB_PATH
            echo "C:\Program Files\Ninja" >> $env:GITHUB_PATH
          fi
        shell: bash

      - name: Add MSVC to PATH
        if: runner.os == 'Windows' && matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Swap Code-Romeo with the version under test
        run: |
          rm -rf Code-Juliett/dependencies/Romeo
          mv Code-Romeo Code-Juliett/dependencies/Romeo
        shell: bash

      - name: Configure and Build
        working-directory: Code-Juliett
        run: |
          mkdir build
          cd build
          cmake -S .. -G Ninja -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build .
        shell: bash

      - name: Run graphical app
        working-directory: Code-Juliett
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a --server-args="-screen 0 1024x768x24" build/bin/Code-Juliett &
            APP_PID=$!
            sleep 5
            kill $APP_PID
          fi
        shell: bash